/**
 * IMAGE REGISTRY — the single place to swap provisional images for final photos.
 *
 * Every image on the site is referenced by an id from this file. All current
 * files are PROVISIONAL illustrations (placeholder: true) generated by
 * `npm run placeholders`. They are NOT photos of Montañas del Tenorio.
 *
 * To use a final photo (see README → "Reemplazar fotografías"):
 *   1. Put the original in photos/<id>.jpg and run `npm run optimize-photos`
 *      (creates public/images/<folder>/<id>-{800,1600}.webp + .jpg).
 *   2. In the entry below: change `src` to the .jpg, set `optimized: true`,
 *      `placeholder: false` and write the real alt text (< 125 chars).
 * The layout reserves space with width/height + aspect-ratio, so nothing moves.
 */
import type { Lang } from '../i18n/routes';

export interface MediaItem {
  src: string;
  width: number;
  height: number;
  alt: Record<Lang, string>;
  /** What the final photo should show (brief for the photographer). */
  brief: string;
  placeholder: boolean;
  /** true when -800.webp / -1600.webp variants exist next to src. */
  optimized?: boolean;
}

type Ratio = '16:9' | '3:2' | '4:3';
const size: Record<Ratio, [number, number]> = {
  '16:9': [1600, 900],
  '3:2': [1200, 800],
  '4:3': [1200, 900],
};

function ph(folder: string, id: string, ratio: Ratio, brief: string, en: string, es: string): [string, MediaItem] {
  const [width, height] = size[ratio];
  return [
    id,
    {
      src: `/images/${folder}/${id}.svg`,
      width,
      height,
      brief,
      placeholder: true,
      alt: {
        en: `Provisional illustration: ${en} (photo coming soon)`,
        es: `Ilustración provisional: ${es} (foto próximamente)`,
      },
    },
  ];
}

export const media: Record<string, MediaItem> = Object.fromEntries([
  // HERO (16:9) — per wireframe: forest/river + couple at cabin + family tubing + wildlife
  ph('hero', 'hero-forest-river', '16:9', 'Río Celeste turquoise water with surrounding forest', 'forest and the turquoise Río Celeste', 'bosque y el Río Celeste turquesa'),
  ph('hero', 'hero-cabin-couple', '16:9', 'Couple relaxing on a cabin terrace facing the forest', 'a couple on a cabin terrace', 'una pareja en la terraza de una cabaña'),
  ph('hero', 'hero-family-tubing', '16:9', 'Family tubing on the river with a guide', 'a family tubing on the river', 'una familia haciendo tubing en el río'),
  ph('hero', 'hero-wildlife', '16:9', 'Wildlife close-up in the forest (bird, frog, etc.)', 'wildlife in the forest', 'vida silvestre en el bosque'),
  // ABOUT
  ph('about', 'founders', '4:3', 'Portrait of the founding family at the property', 'the family behind Montañas del Tenorio', 'la familia detrás de Montañas del Tenorio'),
  ph('about', 'lookout', '4:3', 'View from the lookout on the property', 'the lookout on the property', 'el mirador de la propiedad'),
  // CABINS (3:2)
  ph('cabins', 'cabin-rustic', '3:2', 'Tenorio Cabin — 2 bedrooms and rustic rancho with wood-fired grill (sleeps 7)', 'the Tenorio Cabin', 'la Cabaña Tenorio'),
  ph('cabins', 'cabin-semirustic', '3:2', 'Colibrí Cabin — terrace with chairs and forest view (sleeps 4)', 'the Colibrí Cabin and its terrace', 'la Cabaña Colibrí y su terraza'),
  ph('cabins', 'cabin-accessible', '3:2', 'Tapir Cabin — accessible (Ley 7600), forest view for birdwatching', 'the Tapir Cabin and its forest view', 'la Cabaña Tapir y su vista al bosque'),
  // TOURS (3:2)
  ph('tours', 'tour-tubing', '3:2', 'Guests tubing on Río Celeste with a guide', 'tubing on the river', 'tubing en el río'),
  ph('tours', 'tour-chocolate', '3:2', 'Hands with cacao pods / chocolate making', 'cacao and chocolate', 'cacao y chocolate'),
  ph('tours', 'tour-night-walk', '3:2', 'Guide with flashlight showing a frog at night', 'a guided walk at night', 'una caminata guiada de noche'),
  // GALLERY (4:3) — 4 per category
  ...['1', '2', '3', '4'].map((n) => ph('gallery/forest', `forest-${n}`, '4:3', 'Forest views / lookout / cabins in the forest', `forest view ${n}`, `vista del bosque ${n}`)),
  ...['1', '2', '3', '4'].map((n) => ph('gallery/river', `river-${n}`, '4:3', 'Río Celeste and tubing', `river and tubing ${n}`, `río y tubing ${n}`)),
  ...['1', '2', '3', '4'].map((n) => ph('gallery/wildlife', `wildlife-${n}`, '4:3', 'Birds, frogs and other wildlife on the property', `wildlife ${n}`, `vida silvestre ${n}`)),
  ...['1', '2', '3', '4'].map((n) => ph('gallery/guides', `guides-${n}`, '4:3', 'Specialized guides with guests', `guide with guests ${n}`, `guía con visitantes ${n}`)),
]);

export const gallery = {
  forest: ['forest-1', 'forest-2', 'forest-3', 'forest-4'],
  river: ['river-1', 'river-2', 'river-3', 'river-4'],
  wildlife: ['wildlife-1', 'wildlife-2', 'wildlife-3', 'wildlife-4'],
  guides: ['guides-1', 'guides-2', 'guides-3', 'guides-4'],
} as const;
export type GalleryCategory = keyof typeof gallery;

export const heroSlides = ['hero-forest-river', 'hero-cabin-couple', 'hero-family-tubing', 'hero-wildlife'];

export function getMedia(id: string): MediaItem {
  const m = media[id];
  if (!m) throw new Error(`Unknown media id: ${id}`);
  return m;
}
